# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0b\x44PIDMessage\x12\r\n\x05\x64p_id\x18\x01 \x01(\x05\"(\n\x15QueryDatapathResponse\x12\x0f\n\x07\x63ookies\x18\x01 \x03(\x05\"\x85\x01\n\x10QueryAllResponse\x12+\n\x05tcams\x18\x01 \x03(\x0b\x32\x1c.QueryAllResponse.TcamsEntry\x1a\x44\n\nTcamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.QueryDatapathResponse:\x02\x38\x01\x32\xf0\x04\n\x16PrivilegedProxyService\x12\x36\n\x0cMakeDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x12\x41syncBlockDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\x14\x41syncUnblockDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\x14\x41syncWipeoutDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12;\n\x11SyncBlockDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x13SyncUnblockDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x13SyncWipeoutDatapath\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x12\x37\n\rQueryDatapath\x12\x0c.DPIDMessage\x1a\x16.QueryDatapathResponse\"\x00\x12\x37\n\x08QueryAll\x12\x16.google.protobuf.Empty\x1a\x11.QueryAllResponse\"\x00\x12\x33\n\tCloseNode\x12\x0c.DPIDMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYALLRESPONSE_TCAMSENTRY']._loaded_options = None
  _globals['_QUERYALLRESPONSE_TCAMSENTRY']._serialized_options = b'8\001'
  _globals['_DPIDMESSAGE']._serialized_start=44
  _globals['_DPIDMESSAGE']._serialized_end=72
  _globals['_QUERYDATAPATHRESPONSE']._serialized_start=74
  _globals['_QUERYDATAPATHRESPONSE']._serialized_end=114
  _globals['_QUERYALLRESPONSE']._serialized_start=117
  _globals['_QUERYALLRESPONSE']._serialized_end=250
  _globals['_QUERYALLRESPONSE_TCAMSENTRY']._serialized_start=182
  _globals['_QUERYALLRESPONSE_TCAMSENTRY']._serialized_end=250
  _globals['_PRIVILEGEDPROXYSERVICE']._serialized_start=253
  _globals['_PRIVILEGEDPROXYSERVICE']._serialized_end=877
# @@protoc_insertion_point(module_scope)
