# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proxy_pb2 as proxy__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrivilegedProxyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeDatapath = channel.unary_unary(
                '/PrivilegedProxyService/MakeDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AsyncBlockDatapath = channel.unary_unary(
                '/PrivilegedProxyService/AsyncBlockDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AsyncUnblockDatapath = channel.unary_unary(
                '/PrivilegedProxyService/AsyncUnblockDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AsyncWipeoutDatapath = channel.unary_unary(
                '/PrivilegedProxyService/AsyncWipeoutDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncBlockDatapath = channel.unary_unary(
                '/PrivilegedProxyService/SyncBlockDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncUnblockDatapath = channel.unary_unary(
                '/PrivilegedProxyService/SyncUnblockDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncWipeoutDatapath = channel.unary_unary(
                '/PrivilegedProxyService/SyncWipeoutDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.QueryDatapath = channel.unary_unary(
                '/PrivilegedProxyService/QueryDatapath',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=proxy__pb2.QueryDatapathResponse.FromString,
                _registered_method=True)
        self.QueryAll = channel.unary_unary(
                '/PrivilegedProxyService/QueryAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proxy__pb2.QueryAllResponse.FromString,
                _registered_method=True)
        self.CloseNode = channel.unary_unary(
                '/PrivilegedProxyService/CloseNode',
                request_serializer=proxy__pb2.DPIDMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PrivilegedProxyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncBlockDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncUnblockDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncWipeoutDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncBlockDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUnblockDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncWipeoutDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDatapath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivilegedProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AsyncBlockDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncBlockDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AsyncUnblockDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncUnblockDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AsyncWipeoutDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncWipeoutDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SyncBlockDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncBlockDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SyncUnblockDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUnblockDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SyncWipeoutDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncWipeoutDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'QueryDatapath': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDatapath,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=proxy__pb2.QueryDatapathResponse.SerializeToString,
            ),
            'QueryAll': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proxy__pb2.QueryAllResponse.SerializeToString,
            ),
            'CloseNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseNode,
                    request_deserializer=proxy__pb2.DPIDMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PrivilegedProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PrivilegedProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrivilegedProxyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/MakeDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncBlockDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/AsyncBlockDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncUnblockDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/AsyncUnblockDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncWipeoutDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/AsyncWipeoutDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncBlockDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/SyncBlockDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUnblockDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/SyncUnblockDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncWipeoutDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/SyncWipeoutDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDatapath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/QueryDatapath',
            proxy__pb2.DPIDMessage.SerializeToString,
            proxy__pb2.QueryDatapathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/QueryAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proxy__pb2.QueryAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivilegedProxyService/CloseNode',
            proxy__pb2.DPIDMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
